baseurl = "https://ckaysolution.co.uk/"
languageCode = "en-us"
title = "ckaysolution"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "ckaysolution"
	description = "IT consultant"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "CKAY SOLUTION"

		[params.navigation.links]
			about     = "About us"
			#services  = "Services"
			#portfolio = "Portfolio"
			contact   = "Contact us"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "IT CONSULTANT"
		subtitle   = "The role of an IT consultant is to be a technical specialist that focuses on integrating information technology into businesses and showing clients how to use IT more efficiently to help reach objectives and targets"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Praesentium similique eos eligendi error veritatis harum, sed aliquid totam, quam minus neque enim est architecto, ad. Maiores, aliquid, vitae!"
		company = "Here few more about Company setup and other neccessary details like Registration number is 11234343, With VAT registration 232323423424 @ company house uk"
		buttonText  = "Get started!"


  	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+44-1919066111"
		mobile = "+44 7440559955"
		email = "ckaysolution@gmail.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
